I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/spe/choix_peuple.rpy", line 51, in script
    $ genererFondateur(situation_, traits_)
  File "game/spe/choix_peuple.rpy", line 51, in <module>
    $ genererFondateur(situation_, traits_)
  File "game/spe/choix_peuple.rpy", line 42, in genererFondateur
    situation[fondateur.Fondateur.C_VIOLENCE] = 0
NameError: global name 'fondateur' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/spe/choix_peuple.rpy", line 51, in script
    $ genererFondateur(situation_, traits_)
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/spe/choix_peuple.rpy", line 51, in <module>
    $ genererFondateur(situation_, traits_)
  File "game/spe/choix_peuple.rpy", line 42, in genererFondateur
    situation[fondateur.Fondateur.C_VIOLENCE] = 0
NameError: global name 'fondateur' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
destinFondateur 1.0
Tue Aug 10 19:48:56 2021
